# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.0
_src_path: gh:radio-aktywne/template-app-next
accountname: radio-aktywne
appname: webrecords
description: Broadcast recordings app 📼
docs: true
docsurl: https://radio-aktywne.github.io/webrecords
envprefix: WEBRECORDS
imagename: apps/webrecords
keyprefix: webrecords
port: 38000
registry: true
releases: true
reponame: webrecords
repourl: https://github.com/radio-aktywne/webrecords
