# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.4.0
_src_path: gh:radio-aktywne/template-app-next
accountname: radio-aktywne
appname: magnolia
description: Broadcast recordings app 📼
docs: true
docsurl: https://radio-aktywne.github.io/magnolia
envprefix: MAGNOLIA
imagename: apps/magnolia
keyprefix: magnolia
port: 10720
registry: true
releases: true
reponame: magnolia
repourl: https://github.com/radio-aktywne/magnolia
