services:
  magnolia:
    build:
      context: ./
      network: host
    environment:
      - "MAGNOLIA__SERVER__HOST=${MAGNOLIA__SERVER__HOST:-0.0.0.0}"
      - "MAGNOLIA__SERVER__PORT=${MAGNOLIA__SERVER__PORT:-38000}"
      - "MAGNOLIA__BEAVER__HTTP__SCHEME=${MAGNOLIA__BEAVER__HTTP__SCHEME:-http}"
      - "MAGNOLIA__BEAVER__HTTP__HOST=${MAGNOLIA__BEAVER__HTTP__HOST:-localhost}"
      - "MAGNOLIA__BEAVER__HTTP__PORT=${MAGNOLIA__BEAVER__HTTP__PORT:-35000}"
      - "MAGNOLIA__BEAVER__HTTP__PATH=${MAGNOLIA__BEAVER__HTTP__PATH:-}"
      - "MAGNOLIA__GECKO__HTTP__SCHEME=${MAGNOLIA__GECKO__HTTP__SCHEME:-http}"
      - "MAGNOLIA__GECKO__HTTP__HOST=${MAGNOLIA__GECKO__HTTP__HOST:-localhost}"
      - "MAGNOLIA__GECKO__HTTP__PORT=${MAGNOLIA__GECKO__HTTP__PORT:-31000}"
      - "MAGNOLIA__GECKO__HTTP__PATH=${MAGNOLIA__GECKO__HTTP__PATH:-}"
    network_mode: host
