services:
  magnolia:
    build:
      context: ./
      network: host
    environment:
      - "MAGNOLIA__SERVER__HOST=${MAGNOLIA__SERVER__HOST:-0.0.0.0}"
      - "MAGNOLIA__SERVER__PORT=${MAGNOLIA__SERVER__PORT:-10720}"
      - "MAGNOLIA__SECRETS__AUTH=${MAGNOLIA__SECRETS__AUTH:-secret}"
      - "MAGNOLIA__URLS__PUBLIC=${MAGNOLIA__URLS__PUBLIC:-http://localhost:10720}"
      - "MAGNOLIA__BEAVER__HTTP__SCHEME=${MAGNOLIA__BEAVER__HTTP__SCHEME:-http}"
      - "MAGNOLIA__BEAVER__HTTP__HOST=${MAGNOLIA__BEAVER__HTTP__HOST:-localhost}"
      - "MAGNOLIA__BEAVER__HTTP__PORT=${MAGNOLIA__BEAVER__HTTP__PORT:-10500}"
      - "MAGNOLIA__BEAVER__HTTP__PATH=${MAGNOLIA__BEAVER__HTTP__PATH:-}"
      - "MAGNOLIA__GECKO__HTTP__SCHEME=${MAGNOLIA__GECKO__HTTP__SCHEME:-http}"
      - "MAGNOLIA__GECKO__HTTP__HOST=${MAGNOLIA__GECKO__HTTP__HOST:-localhost}"
      - "MAGNOLIA__GECKO__HTTP__PORT=${MAGNOLIA__GECKO__HTTP__PORT:-10700}"
      - "MAGNOLIA__GECKO__HTTP__PATH=${MAGNOLIA__GECKO__HTTP__PATH:-}"
      - "MAGNOLIA__SCORPION__PUBLIC__SCHEME=${MAGNOLIA__SCORPION__PUBLIC__SCHEME:-http}"
      - "MAGNOLIA__SCORPION__PUBLIC__HOST=${MAGNOLIA__SCORPION__PUBLIC__HOST:-localhost}"
      - "MAGNOLIA__SCORPION__PUBLIC__PORT=${MAGNOLIA__SCORPION__PUBLIC__PORT:-20000}"
      - "MAGNOLIA__SCORPION__PUBLIC__PATH=${MAGNOLIA__SCORPION__PUBLIC__PATH:-}"
      - "MAGNOLIA__SCORPION__PUBLIC__CLIENT=${MAGNOLIA__SCORPION__PUBLIC__CLIENT:-magnolia}"
      - "MAGNOLIA__SCORPION__PUBLIC__SECRET=${MAGNOLIA__SCORPION__PUBLIC__SECRET:-secret}"
      - "MAGNOLIA__DEBUG=${MAGNOLIA__DEBUG:-true}"
    network_mode: host
