services:
  magnolia:
    build:
      context: ./
      network: host
    environment:
      - "MAGNOLIA__APIS__BEAVER__HOST=${MAGNOLIA__APIS__BEAVER__HOST:-localhost}"
      - "MAGNOLIA__APIS__BEAVER__PATH=${MAGNOLIA__APIS__BEAVER__PATH:-}"
      - "MAGNOLIA__APIS__BEAVER__PORT=${MAGNOLIA__APIS__BEAVER__PORT:-10500}"
      - "MAGNOLIA__APIS__BEAVER__SCHEME=${MAGNOLIA__APIS__BEAVER__SCHEME:-http}"
      - "MAGNOLIA__APIS__GECKO__HOST=${MAGNOLIA__APIS__GECKO__HOST:-localhost}"
      - "MAGNOLIA__APIS__GECKO__PATH=${MAGNOLIA__APIS__GECKO__PATH:-}"
      - "MAGNOLIA__APIS__GECKO__PORT=${MAGNOLIA__APIS__GECKO__PORT:-10700}"
      - "MAGNOLIA__APIS__GECKO__SCHEME=${MAGNOLIA__APIS__GECKO__SCHEME:-http}"
      - "MAGNOLIA__APIS__ICANHAZDADJOKE__HOST=${MAGNOLIA__APIS__ICANHAZDADJOKE__HOST:-icanhazdadjoke.com}"
      - "MAGNOLIA__APIS__ICANHAZDADJOKE__PATH=${MAGNOLIA__APIS__ICANHAZDADJOKE__PATH:-}"
      - "MAGNOLIA__APIS__ICANHAZDADJOKE__PORT=${MAGNOLIA__APIS__ICANHAZDADJOKE__PORT:-}"
      - "MAGNOLIA__APIS__ICANHAZDADJOKE__SCHEME=${MAGNOLIA__APIS__ICANHAZDADJOKE__SCHEME:-https}"
      - "MAGNOLIA__DEBUG=${MAGNOLIA__DEBUG:-true}"
      - "MAGNOLIA__SERVER__HOST=${MAGNOLIA__SERVER__HOST:-0.0.0.0}"
      - "MAGNOLIA__SERVER__PORT=${MAGNOLIA__SERVER__PORT:-10720}"
    network_mode: host
