// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const UploadRequestTypeSchema = z.string();

export const UploadRequestStartSchema = z.iso.datetime({
  offset: true,
  local: true,
});

export const UploadRequestEventSchema = z.uuid();

/**
 * Result
 *
 * Result of the test.
 */
export const TestResponseResultSchema = z
  .object({
    success: z.boolean().register(z.globalRegistry, {
      description: "Indicates if the test was successful.",
    }),
    message: z.string().register(z.globalRegistry, {
      description: "Message returned from the test.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Result of the test.",
  });

/**
 * Parameters
 *
 * Parameters for testing.
 */
export const ParametersSchema = z
  .object({
    message: z.string().nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Parameters for testing.",
  });

export const TestRequestParametersSchema = ParametersSchema.nullable();

/**
 * EventType
 *
 * Event types.
 */
export const EventTypeSchema = z.enum(["test"]).register(z.globalRegistry, {
  description: "Event types.",
});

export const SubscribeRequestTypesSchema = z
  .union([z.string(), z.array(EventTypeSchema)])
  .nullable();

export const NaiveDatetimeSchema = z.iso.datetime({
  offset: true,
  local: true,
});

/**
 * Recording
 *
 * Recording data.
 */
export const RecordingSchema = z
  .object({
    event: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the event.",
    }),
    start: NaiveDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Recording data.",
  });

/**
 * RecordingList
 *
 * List of recordings.
 */
export const ListResponseResultsSchema = z
  .object({
    count: z.int().register(z.globalRegistry, {
      description: "Total number of recordings that match the request.",
    }),
    limit: z.int().nullable(),
    offset: z.int().nullable(),
    recordings: z.array(RecordingSchema).register(z.globalRegistry, {
      description: "List of recordings.",
    }),
  })
  .register(z.globalRegistry, {
    description: "List of recordings.",
  });

/**
 * ListOrder
 *
 * Order to list recordings.
 */
export const ListOrderSchema = z
  .enum(["asc", "desc"])
  .register(z.globalRegistry, {
    description: "Order to list recordings.",
  });

export const ListRequestOrderSchema = ListOrderSchema.nullable();

export const ListRequestOffsetSchema = z.int().nullable();

export const ListRequestLimitSchema = z.int().nullable();

export const ListRequestEventSchema = z.uuid();

export const ListRequestBeforeSchema = NaiveDatetimeSchema.nullable();

export const ListRequestAfterSchema = NaiveDatetimeSchema.nullable();

export const HeadDownloadRequestStartSchema = z.iso.datetime({
  offset: true,
  local: true,
});

export const HeadDownloadRequestEventSchema = z.uuid();

export const DownloadRequestStartSchema = z.iso.datetime({
  offset: true,
  local: true,
});

export const DownloadRequestEventSchema = z.uuid();

export const DeleteRequestStartSchema = z.iso.datetime({
  offset: true,
  local: true,
});

export const DeleteRequestEventSchema = z.uuid();

export const PingPingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const PingPingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const PingHeadpingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const PingHeadpingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const RecordingsEventStartDeleteRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    event: DeleteRequestEventSchema,
    start: DeleteRequestStartSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const RecordingsEventStartDeleteResponseSchema = z
  .void()
  .register(z.globalRegistry, {
    description: "Request fulfilled, nothing follows",
  });

export const RecordingsEventStartDownloadRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    event: DownloadRequestEventSchema,
    start: DownloadRequestStartSchema,
  }),
  query: z.never().optional(),
});

/**
 * Stream Response
 */
export const RecordingsEventStartDownloadResponseSchema = z
  .unknown()
  .register(z.globalRegistry, {
    description: "Stream Response",
  });

export const RecordingsEventStartHeaddownloadRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    event: HeadDownloadRequestEventSchema,
    start: HeadDownloadRequestStartSchema,
  }),
  query: z.never().optional(),
});

export const RecordingsEventStartUploadRequestSchema = z.object({
  body: z.unknown(),
  path: z.object({
    event: UploadRequestEventSchema,
    start: UploadRequestStartSchema,
  }),
  query: z.never().optional(),
  headers: z.object({
    "content-type": z.union([UploadRequestTypeSchema, z.string()]),
  }),
});

/**
 * Request fulfilled, nothing follows
 */
export const RecordingsEventStartUploadResponseSchema = z
  .void()
  .register(z.globalRegistry, {
    description: "Request fulfilled, nothing follows",
  });

export const RecordingsEventListRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    event: ListRequestEventSchema,
  }),
  query: z
    .object({
      after: z.union([ListRequestAfterSchema, z.string()]).nullish(),
      before: z.union([ListRequestBeforeSchema, z.string()]).nullish(),
      limit: z.union([ListRequestLimitSchema, z.string()]).nullish(),
      offset: z.union([ListRequestOffsetSchema, z.string()]).nullish(),
      order: z.union([ListRequestOrderSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const RecordingsEventListResponseSchema = ListResponseResultsSchema;

export const SseSubscribeRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      types: z.union([SubscribeRequestTypesSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, stream of Server-Sent Events follows
 */
export const SseSubscribeResponseSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Request fulfilled, stream of Server-Sent Events follows",
  });

export const TestTestRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      parameters: z.union([TestRequestParametersSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TestTestResponseSchema = TestResponseResultSchema;
