// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import {
  PingHeadpingRequestSchema,
  PingHeadpingResponseSchema,
  PingPingRequestSchema,
  PingPingResponseSchema,
  RecordingsEventListRequestSchema,
  RecordingsEventListResponseSchema,
  RecordingsEventStartDeleteRequestSchema,
  RecordingsEventStartDeleteResponseSchema,
  RecordingsEventStartDownloadRequestSchema,
  RecordingsEventStartDownloadResponseSchema,
  RecordingsEventStartHeaddownloadRequestSchema,
  RecordingsEventStartUploadRequestSchema,
  RecordingsEventStartUploadResponseSchema,
  SseSubscribeRequestSchema,
  SseSubscribeResponseSchema,
  TestTestRequestSchema,
  TestTestResponseSchema,
} from "./schemas";
import type {
  PingHeadpingRequest,
  PingHeadpingResponses,
  PingPingRequest,
  PingPingResponses,
  RecordingsEventListErrors,
  RecordingsEventListRequest,
  RecordingsEventListResponses,
  RecordingsEventStartDeleteErrors,
  RecordingsEventStartDeleteRequest,
  RecordingsEventStartDeleteResponses,
  RecordingsEventStartDownloadErrors,
  RecordingsEventStartDownloadRequest,
  RecordingsEventStartDownloadResponses,
  RecordingsEventStartHeaddownloadErrors,
  RecordingsEventStartHeaddownloadRequest,
  RecordingsEventStartHeaddownloadResponses,
  RecordingsEventStartUploadErrors,
  RecordingsEventStartUploadRequest,
  RecordingsEventStartUploadResponses,
  SseSubscribeErrors,
  SseSubscribeRequest,
  SseSubscribeResponses,
  TestTestErrors,
  TestTestRequest,
  TestTestResponses,
} from "./types";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

class HeyApiClient {
  protected client: Client;

  constructor(args: { client: Client }) {
    this.client = args.client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = "default";

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(
        `No SDK client found. Create one with "new Sdk()" to fix this error.`,
      );
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class Sdk extends HeyApiClient {
  public static readonly __registry = new HeyApiRegistry<Sdk>();

  constructor(args: { client: Client; key?: string }) {
    super(args);
    Sdk.__registry.set(this, args.key);
  }

  /**
   * Ping
   *
   * Ping.
   */
  public pingPing<ThrowOnError extends boolean = false>(
    options?: Options<PingPingRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      PingPingResponses,
      unknown,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await PingPingRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await PingPingResponseSchema.parseAsync(data),
      url: "/ping",
      ...options,
    });
  }

  /**
   * Ping headers
   *
   * Ping headers.
   */
  public pingHeadping<ThrowOnError extends boolean = false>(
    options?: Options<PingHeadpingRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).head<
      PingHeadpingResponses,
      unknown,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await PingHeadpingRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await PingHeadpingResponseSchema.parseAsync(data),
      url: "/ping",
      ...options,
    });
  }

  /**
   * Delete recording
   *
   * Delete a recording.
   */
  public recordingsEventStartDelete<ThrowOnError extends boolean = false>(
    options: Options<RecordingsEventStartDeleteRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).delete<
      RecordingsEventStartDeleteResponses,
      RecordingsEventStartDeleteErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await RecordingsEventStartDeleteRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await RecordingsEventStartDeleteResponseSchema.parseAsync(data),
      url: "/recordings/{event}/{start}",
      ...options,
    });
  }

  /**
   * Download recording
   *
   * Download a recording.
   */
  public recordingsEventStartDownload<ThrowOnError extends boolean = false>(
    options: Options<RecordingsEventStartDownloadRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      RecordingsEventStartDownloadResponses,
      RecordingsEventStartDownloadErrors,
      ThrowOnError
    >({
      parseAs: "stream",
      requestValidator: async (data) =>
        await RecordingsEventStartDownloadRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await RecordingsEventStartDownloadResponseSchema.parseAsync(data),
      url: "/recordings/{event}/{start}",
      ...options,
    });
  }

  /**
   * Download recording headers
   *
   * Download recording headers.
   */
  public recordingsEventStartHeaddownload<ThrowOnError extends boolean = false>(
    options: Options<RecordingsEventStartHeaddownloadRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).head<
      RecordingsEventStartHeaddownloadResponses,
      RecordingsEventStartHeaddownloadErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await RecordingsEventStartHeaddownloadRequestSchema.parseAsync(data),
      url: "/recordings/{event}/{start}",
      ...options,
    });
  }

  /**
   * Upload recording
   *
   * Upload a recording.
   */
  public recordingsEventStartUpload<ThrowOnError extends boolean = false>(
    options: Options<RecordingsEventStartUploadRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).put<
      RecordingsEventStartUploadResponses,
      RecordingsEventStartUploadErrors,
      ThrowOnError
    >({
      bodySerializer: null,
      // @ts-expect-error
      duplex: "half",
      requestValidator: async (data) =>
        await RecordingsEventStartUploadRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await RecordingsEventStartUploadResponseSchema.parseAsync(data),
      url: "/recordings/{event}/{start}",
      ...options,
    });
  }

  /**
   * List recordings
   *
   * List recordings.
   */
  public recordingsEventList<ThrowOnError extends boolean = false>(
    options: Options<RecordingsEventListRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      RecordingsEventListResponses,
      RecordingsEventListErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await RecordingsEventListRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await RecordingsEventListResponseSchema.parseAsync(data),
      url: "/recordings/{event}",
      ...options,
    });
  }

  /**
   * Get SSE stream
   *
   * Get a stream of Server-Sent Events.
   */
  public sseSubscribe<ThrowOnError extends boolean = false>(
    options?: Options<SseSubscribeRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).sse.get<
      SseSubscribeResponses,
      SseSubscribeErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await SseSubscribeRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await SseSubscribeResponseSchema.parseAsync(data),
      url: "/sse",
      ...options,
    });
  }

  /**
   * Test
   *
   * Test.
   */
  public testTest<ThrowOnError extends boolean = false>(
    options?: Options<TestTestRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      TestTestResponses,
      TestTestErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await TestTestRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await TestTestResponseSchema.parseAsync(data),
      url: "/test",
      ...options,
    });
  }
}
