// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type UploadRequestType = string;

export type UploadRequestStart = string;

export type UploadRequestEvent = string;

/**
 * Result
 *
 * Result of the test.
 */
export type TestResponseResult = {
  /**
   * Success
   *
   * Indicates if the test was successful.
   */
  success: boolean;
  /**
   * Message
   *
   * Message returned from the test.
   */
  message: string;
};

export type TestRequestParameters = Parameters | null;

/**
 * Parameters
 *
 * Parameters for testing.
 */
export type Parameters = {
  /**
   * Message
   *
   * Optional message to include in the test.
   */
  message?: string | null;
};

export type SubscribeRequestTypes = string | Array<EventType> | null;

/**
 * EventType
 *
 * Event types.
 */
export type EventType = "test";

/**
 * Recording
 *
 * Recording data.
 */
export type Recording = {
  /**
   * Event
   *
   * Identifier of the event.
   */
  event: string;
  start: NaiveDatetime;
};

export type NaiveDatetime = string;

/**
 * RecordingList
 *
 * List of recordings.
 */
export type ListResponseResults = {
  /**
   * Count
   *
   * Total number of recordings that match the request.
   */
  count: number;
  /**
   * Limit
   *
   * Maximum number of returned recordings.
   */
  limit: number | null;
  /**
   * Offset
   *
   * Number of skipped recordings.
   */
  offset: number | null;
  /**
   * Recordings
   *
   * List of recordings.
   */
  recordings: Array<Recording>;
};

export type ListRequestOrder = ListOrder | null;

/**
 * ListOrder
 *
 * Order to list recordings.
 */
export type ListOrder = "asc" | "desc";

export type ListRequestOffset = number | null;

export type ListRequestLimit = number | null;

export type ListRequestEvent = string;

export type ListRequestBefore = NaiveDatetime | null;

export type ListRequestAfter = NaiveDatetime | null;

export type HeadDownloadRequestStart = string;

export type HeadDownloadRequestEvent = string;

export type DownloadRequestStart = string;

export type DownloadRequestEvent = string;

export type DeleteRequestStart = string;

export type DeleteRequestEvent = string;

export type PingPingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingPingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingPingResponse = PingPingResponses[keyof PingPingResponses];

export type PingHeadpingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingHeadpingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingHeadpingResponse =
  PingHeadpingResponses[keyof PingHeadpingResponses];

export type RecordingsEventStartDeleteRequest = {
  body?: never;
  path: {
    event: DeleteRequestEvent;
    start: DeleteRequestStart;
  };
  query?: never;
  url: "/recordings/{event}/{start}";
};

export type RecordingsEventStartDeleteErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type RecordingsEventStartDeleteError =
  RecordingsEventStartDeleteErrors[keyof RecordingsEventStartDeleteErrors];

export type RecordingsEventStartDeleteResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type RecordingsEventStartDeleteResponse =
  RecordingsEventStartDeleteResponses[keyof RecordingsEventStartDeleteResponses];

export type RecordingsEventStartDownloadRequest = {
  body?: never;
  path: {
    event: DownloadRequestEvent;
    start: DownloadRequestStart;
  };
  query?: never;
  url: "/recordings/{event}/{start}";
};

export type RecordingsEventStartDownloadErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type RecordingsEventStartDownloadError =
  RecordingsEventStartDownloadErrors[keyof RecordingsEventStartDownloadErrors];

export type RecordingsEventStartDownloadResponses = {
  /**
   * Stream Response
   */
  200: ReadableStream;
};

export type RecordingsEventStartDownloadResponse =
  RecordingsEventStartDownloadResponses[keyof RecordingsEventStartDownloadResponses];

export type RecordingsEventStartHeaddownloadRequest = {
  body?: never;
  path: {
    event: HeadDownloadRequestEvent;
    start: HeadDownloadRequestStart;
  };
  query?: never;
  url: "/recordings/{event}/{start}";
};

export type RecordingsEventStartHeaddownloadErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type RecordingsEventStartHeaddownloadError =
  RecordingsEventStartHeaddownloadErrors[keyof RecordingsEventStartHeaddownloadErrors];

export type RecordingsEventStartHeaddownloadResponses = {
  /**
   * Request fulfilled, headers follow
   */
  200: unknown;
};

export type RecordingsEventStartUploadRequest = {
  body: ReadableStream;
  headers: {
    /**
     * UploadRequestType
     *
     * Type of the recording data.
     */
    "Content-Type": UploadRequestType | string;
  };
  path: {
    event: UploadRequestEvent;
    start: UploadRequestStart;
  };
  query?: never;
  url: "/recordings/{event}/{start}";
};

export type RecordingsEventStartUploadErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type RecordingsEventStartUploadError =
  RecordingsEventStartUploadErrors[keyof RecordingsEventStartUploadErrors];

export type RecordingsEventStartUploadResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type RecordingsEventStartUploadResponse =
  RecordingsEventStartUploadResponses[keyof RecordingsEventStartUploadResponses];

export type RecordingsEventListRequest = {
  body?: never;
  path: {
    event: ListRequestEvent;
  };
  query?: {
    /**
     * Only list recordings after this datetime (in event timezone).
     */
    after?: ListRequestAfter | string | null;
    /**
     * Only list recordings before this datetime (in event timezone).
     */
    before?: ListRequestBefore | string | null;
    /**
     * Maximum number of recordings to return. Default is 10.
     */
    limit?: ListRequestLimit | string | null;
    /**
     * Number of recordings to skip.
     */
    offset?: ListRequestOffset | string | null;
    /**
     * Order to apply to the results.
     */
    order?: ListRequestOrder | string | null;
  };
  url: "/recordings/{event}";
};

export type RecordingsEventListErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type RecordingsEventListError =
  RecordingsEventListErrors[keyof RecordingsEventListErrors];

export type RecordingsEventListResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: ListResponseResults;
};

export type RecordingsEventListResponse =
  RecordingsEventListResponses[keyof RecordingsEventListResponses];

export type SseSubscribeRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Types of events to subscribe to.
     */
    types?: SubscribeRequestTypes | string | null;
  };
  url: "/sse";
};

export type SseSubscribeErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type SseSubscribeError = SseSubscribeErrors[keyof SseSubscribeErrors];

export type SseSubscribeResponses = {
  /**
   * Request fulfilled, stream of Server-Sent Events follows
   */
  200: string;
};

export type SseSubscribeResponse =
  SseSubscribeResponses[keyof SseSubscribeResponses];

export type TestTestRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Parameters for testing.
     */
    parameters?: TestRequestParameters | string | null;
  };
  url: "/test";
};

export type TestTestErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TestTestError = TestTestErrors[keyof TestTestErrors];

export type TestTestResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: TestResponseResult;
};

export type TestTestResponse = TestTestResponses[keyof TestTestResponses];
