/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  "/ping": {
    delete?: never;
    /**
     * Ping
     * @description Ping.
     */
    get: operations["PingPing"];
    /**
     * Ping headers
     * @description Ping headers.
     */
    head: operations["PingHeadping"];
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
  "/records/{event}": {
    delete?: never;
    /**
     * List records
     * @description List records.
     */
    get: operations["RecordsEventList"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
  "/records/{event}/{start}": {
    /**
     * Delete record
     * @description Delete a record.
     */
    delete: operations["RecordsEventStartDelete"];
    /**
     * Download record
     * @description Download a record.
     */
    get: operations["RecordsEventStartDownload"];
    /**
     * Download record headers
     * @description Download record headers.
     */
    head: operations["RecordsEventStartHeaddownload"];
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    /**
     * Upload record
     * @description Upload a record.
     */
    put: operations["RecordsEventStartUpload"];
    trace?: never;
  };
};
export type webhooks = { [key: string]: never };
export type components = {
  headers: never;
  parameters: never;
  pathItems: never;
  requestBodies: never;
  responses: never;
  schemas: {
    /** Record */
    Record: {
      /**
       * Format: uuid
       * @description Identifier of the event.
       */
      event: string;
      /**
       * Format: date-time
       * @description Start time of the event instance in event timezone.
       */
      start: string;
    };
    /** RecordList */
    RecordList: {
      /** @description Total number of records that match the request. */
      count: number;
      /** @description Maximum number of returned records. */
      limit?: null | number;
      /** @description Number of skipped records. */
      offset?: null | number;
      /** @description List of records. */
      records: components["schemas"]["Record"][];
    };
  };
};
export type $defs = { [key: string]: never };
export type operations = {
  PingHeadping: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
          "cache-control"?: string;
        };
      };
    };
  };
  PingPing: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
          "cache-control"?: string;
        };
      };
    };
  };
  RecordsEventList: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the event to list records for. */
        event: string;
      };
      query?: {
        /** @description Only list records after this time (in event timezone). */
        after?: null | string;
        /** @description Only list records before this time (in event timezone). */
        before?: null | string;
        /** @description Maximum number of records to return. */
        limit?: null | number;
        /** @description Number of records to skip. */
        offset?: null | number;
        /** @description Order to apply to the results. */
        order?: "asc" | "desc" | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": components["schemas"]["RecordList"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  RecordsEventStartDelete: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the event. */
        event: string;
        /** @description Start time of the event instance in event timezone. */
        start: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  RecordsEventStartDownload: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the event. */
        event: string;
        /** @description Start time of the event instance in event timezone. */
        start: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stream Response */
      200: {
        content: {
          "": string;
        };
        headers: {
          [name: string]: unknown;
          /** @description File size in bytes */
          "content-length"?: string;
          /** @description Content length. */
          "Content-Length"?: unknown;
          /** @description Content type. */
          "Content-Type"?: unknown;
          /** @description Entity tag */
          etag?: string;
          /** @description Entity tag. */
          ETag?: unknown;
          /** @description Last modified data-time in RFC 2822 format */
          "last-modified"?: string;
          /** @description Last modified. */
          "Last-Modified"?: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  RecordsEventStartHeaddownload: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description Identifier of the event. */
        event: string;
        /** @description Start time of the event instance in event timezone. */
        start: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
          /** @description Content length. */
          "Content-Length"?: unknown;
          /** @description Content type. */
          "Content-Type"?: unknown;
          /** @description Entity tag. */
          ETag?: unknown;
          /** @description Last modified. */
          "Last-Modified"?: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  RecordsEventStartUpload: {
    parameters: {
      cookie?: never;
      header: {
        /** @description Type of the record data. */
        "Content-Type": string;
      };
      path: {
        /** @description Identifier of the event. */
        event: string;
        /** @description Start time of the event instance in event timezone. */
        start: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
};
